#pragma once
struct particle {
	//Type of this particle.
	//Type id is generated by the compiler, with one id per
	//type of particle.
	int type;

	//Two versions of the particle data,
	//each points to a "struct <particle_name>"
	void *data[2];
};
