#pragma once
#include <export.h>
#include <tag.h>
#include <list.h>
#include <objpool.h>
struct particle {
	//Type of this particle.
	//Type id is generated by the compiler, with one id per
	//type of particle.
	int type;

	//Two versions of the particle data,
	//each points to a "struct <particle_name>"
	union particle_variants data[2];

	//Current version of this partcile
	int current;

	struct tag t;
	struct list_head hitboxes;
	struct list_head actors;
	struct list_node next_changed;
	struct list_node q;

	bool changed;
	bool deleted;
};

objpool_proto(struct particle, particle)

void mark_particle_as_changed(struct particle *);
struct particle *first_particle(void);
struct particle *next_particle(struct particle *);

extern struct list_head changed_particles, all_particles;

