#pragma once
#include <export.h>
#include <tag.h>
#include <list.h>
struct particle {
	//Type of this particle.
	//Type id is generated by the compiler, with one id per
	//type of particle.
	int type;

	//Two versions of the particle data,
	//each points to a "struct <particle_name>"
	union particle_variants data[2];

	//Current version of this partcile
	int current;

	struct tag t;
	struct list_head hitboxes;
	struct list_head actors;
	struct list_node next_changed;

	bool changed;
};

struct particle *alloc_particle(void);
void free_particle(struct particle *);
int get_particle_id(struct particle *);
void mark_particle_as_changed(struct particle *);

extern struct list_head changed_particles;

